name: Komplett

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/getitdigital/texcontainer:main

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: compile Skript
      id: skript
      working-directory: ./
      run: latexmk -interaction=nonstopmode -file-line-error -pdf --shell-escape -outdir=TeXAux Skript.tex
    - name: Upload Skript as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Komplett-Skript
        path: TeXAux/Skript.pdf
    - name: upload to server
      shell: bash
      run: |
        echo "Uploading Skript.pdf to server"
        which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
        mkdir -p ~/.ssh
        eval $(ssh-agent -s)
        [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        chmod 400 ~/.ssh/config
        ssh-add <(echo "${{secrets.SFTP_KEY}}")
        sftp ${{secrets.SFTP_USERNAME}}@${{secrets.SFTP_SERVER}}:komplett <<< $'put TeXAux/*'
